export const FETCH_PRODUCTS_START = 'FETCH_PRODUCTS_START';
export const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS';
export const FETCH_PRODUCTS_ERROR = 'FETCH_PRODUCTS_ERROR';
export const SET_TRENDING_PRODUCTS = 'SET_TRENDING_PRODUCTS';
export const SET_BEST_SELLERS = 'SET_BEST_SELLERS';
