export const FETCH_PRODUCTS_START = 'FETCH_PRODUCTS_START';
export const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS';
export const FETCH_PRODUCTS_ERROR = 'FETCH_PRODUCTS_ERROR';
export const SET_TRENDING_PRODUCTS = 'SET_TRENDING_PRODUCTS';
export const SET_BEST_SELLERS = 'SET_BEST_SELLERS';

export const FETCH_ARTICLES_START = 'FETCH_ARTICLES_START';
export const FETCH_ARTICLES_SUCCESS = 'FETCH_ARTICLES_SUCCESS';
export const FETCH_ARTICLES_ERROR = 'FETCH_ARTICLES_ERROR';
export const GET_LAST_ARTICLES = 'GET_LAST_ARTICLES';

export const TOGGLE_CART = 'TOGGLE_CART';
export const ADD_PRODUCT_TO_CART = 'ADD_PRODUCT_TO_CART';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';
